apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: starlancer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: starlancer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: starlancer
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: HTTP_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.authSecretName }}
                  key: username
            - name: HTTP_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.authSecretName }}
                  key: password
          readinessProbe:
            tcpSocket:
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
